# Generated by Django 5.0.6 on 2024-08-21 15:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0002_add_person_school_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 15, 42, 23, 368672, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ModelApp.place')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
